### PR TITLE
Puzsoc 1236 update game docs

### PR DESCRIPTION
**Pull request by ctrble**
## Description

Update to expected save state shape, clarification on types and required/optional.

- [x] This is appropriate for public visibility

## Links

- Jira Issue: PUZSOC-1236

### CODE REVIEW

**Review by ShaneB007 — APPROVED** [review]
Looks solid, gives a clear representation of what data is needed and what is optional, as well as lining out our new snapshot object.

**Comment by ctrble** [comment]
@Andrews-McMeel-Universal/graphite_labs, @Andrews-McMeel-Universal/enter-the-studio, @Andrews-McMeel-Universal/killabunnies, @Andrews-McMeel-Universal/cangrejo, this change was requested by our BE team, please reach out if you have any questions or concerns about this update!

**Review by miltoncandelero — APPROVED** [review]
Looks good! Implemented on our side. You will get a barrage of deploys soon 😅

**Review by mmartis — APPROVED** [review]

**Review by abarrows — COMMENTED** [review]
LGTM!

**Pull request merged**
