### PR TITLE
Puzsoc 3066 document sticky settings

### PR DESCRIPTION
**Pull request by ctrble**
## Description

Adding documentation for the new `loadSettings` command.

- [x] This is appropriate for public visibility

## Links

- Jira Issue: PUZSOC-3066

### CODE REVIEW

**Comment by ctrble** [comment]
@axufurisamu @tfie-amuniversal @AMU-JoeSitt giving you all first pass at this. If this looks consistent with what you expect, then please approve and I'll add additional reviewers.

**Review by tfie-amuniversal — DISMISSED** [review]

**Comment by ctrble** [comment]
@Andrews-McMeel-Universal/cangrejo @Andrews-McMeel-Universal/enter-the-studio @Andrews-McMeel-Universal/killabunnies 

Hey all! These spec updates related to some planned enhancements for how settings are saved (we'll be in contact about those changes), but in the meantime please read through, ask questions/raise concerns if you have them, and approve this if it looks ok to you!

**Review by etsaaron — DISMISSED** [review]

**Comment by mmartis** [comment]
> @Andrews-McMeel-Universal/cangrejo @Andrews-McMeel-Universal/enter-the-studio @Andrews-McMeel-Universal/killabunnies
> 
> Hey all! These spec updates related to some planned enhancements for how settings are saved (we'll be in contact about those changes), but in the meantime please read through, ask questions/raise concerns if you have them, and approve this if it looks ok to you!

Hey @ctrble 

Are Sticky Settings fixed on your end or support any key in the object? Is flexible enough as `amuGame.state.snapshot` or can only include the keys in the docs?

```javascript
loadSettings: {
    autoNotes: false,
    darkMode: false,
    jumpToFirstEmpty: false,
    jumpToNextClue: false,
    showRelated: false,
    skipFilled: false,
    sound: false,
    visualTimer: false,
  }
```

**Comment by ctrble** [comment]
> Are Sticky Settings fixed on your end or support any key in the object? Is flexible enough as amuGame.state.snapshot or can only include the keys in the docs?

@mmartis good question, they are fixed. These sticky settings are used in a fairly wide context, so we want them to be as consistent as possible. If there are any settings in a game that are not included in that list, then those settings should be stored inside `amuGame.state.snapshot`. Let me know if there are any settings in particular you've got questions or concerns about!

**Review by mmartis — DISMISSED** [review]

**Comment by etsaaron** [comment]
@ctrble does this change how we send messages from the game as well? Should there be an amuGame.settings object in addition to the amuGame.state object when the user changes settings?

**Comment by ctrble** [comment]
> @ctrble does this change how we send messages from the game as well? Should there be an amuGame.settings object in addition to the amuGame.state object when the user changes settings?

@etsaaron, no need for that. We're listening to the new data in `amuGame.event.details` to catch those changes. Does that help clarify?

**Comment by etsaaron** [comment]
@ctrble It does! Just wanted to double check now that I'm making these changes

**Comment by ctrble** [comment]
> @ctrble It does! Just wanted to double check now that I'm making these changes

Great! Let me know if you run into anything else along the way!

**Review by etsaaron — APPROVED** [review]

**Comment by ctrble** [comment]
@tfie-amuniversal could i get another +1 on this one? Had to stale your review and I want to get this merged in.

**Review by mmartis — APPROVED** [review]

**Review by tfie-amuniversal — APPROVED** [review]

**Pull request merged**
